### ISSUE TITLE
Mnist

### ISSUE THREAD

**Issue by DanikKamilov** [ENCP/CNNdroid#14]
Hi. I try to use cnndroid for mnist recognition from examples. And it crashed in "for_each_root()" method in F8OutF1 FullyConnected Layer. Can you add some simple working example for Lenet? Must I use inputButch or inputSingle?

**Comment by latifisalar** [comment]
Hi,
Can you send some of your logcat so I can have a better idea what's wrong in your application?
You can use either inputSingle (3d array containing raw data of a single image) or inputBatch (4d array for multiple images) depending on your requirements, but using inputBatch can result in a moderate performance gain in average.

**Comment by DanikKamilov** [comment]
I don't know why, but application closed when try use rsnScriptForEach(mContext, id, slot, ains, aout, params, limits);
(I try to test on LeNet example. My caffemodel and prototxt files without changes. and I use yours Lenet_def.txt example file to cnndroid.
I use android.gesture.GestureOverlayView to create the picture of digit.

 ```
 bmpFromGesture = Bitmap.createBitmap(gesture.getDrawingCache());
 bmp= Bitmap.createScaledBitmap(bmpFromGesture, 227, 227, false);

 for (int j = 0; j < 227; ++j)
            for (int k = 0; k < 227; ++k) {
                int color = bmp.getPixel(j, k);
                inputBatch[0][0][k][j] = (float) (blue(color)) - (float) 104.0079317889;
                inputBatch[0][1][k][j] = (float) (green(color)) - (float) 116.66876761696767;
                inputBatch[0][2][k][j] = (float) (red(color)) - (float) 122.6789143406786;
            }

   Object output = myConv.compute(inputBatch);
```

is that right?


This cycle works fine for 0-3 iterations (conv pull conv pull layers) 

```
for (int i = 0 ; i < layers.size() ; i++) {
            Object temp = output;
            output = layers.get(i).compute(output);
        }
```

4 iteration (full connected layer) - close my application. ( and may be it will helpful - I use SDK 24 version)

logcat:

> 03-19 14:50:57.236 26241-26241/app.dikeys.cnndroidmnist D/CNNdroid: layers.conv1: Computation Run Time = 203
> 03-19 14:50:57.301 26241-26241/app.dikeys.cnndroidmnist D/CNNdroid: layers.pool1: Computation Run Time = 65
> 03-19 14:50:57.525 26241-26241/app.dikeys.cnndroidmnist D/CNNdroid: layers.conv2: Computation Run Time = 224
> 03-19 14:50:57.541 26241-26241/app.dikeys.cnndroidmnist D/CNNdroid: layers.pool2: Computation Run Time = 16
> 03-19 14:50:57.596 26241-26300/app.dikeys.cnndroidmnist A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f67c80000 in tid 26300 (s.cnndroidmnist)
> 03-19 14:50:57.597 26241-26308/app.dikeys.cnndroidmnist A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f67c80000 in tid 26308 (s.cnndroidmnist)
> 03-19 14:50:57.597 26241-26308/app.dikeys.cnndroidmnist I/libc: Another thread contacted debuggerd first; not contacting debuggerd.
> 03-19 14:50:57.602 26241-26304/app.dikeys.cnndroidmnist A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f67c80000 in tid 26304 (s.cnndroidmnist)
> 03-19 14:50:57.602 26241-26304/app.dikeys.cnndroidmnist I/libc: Another thread contacted debuggerd first; not contacting debuggerd.



and i have this parameters when app comes to rsnScriptForEach(mContext, id, slot, ains, aout, params, limits);
![params](https://cloud.githubusercontent.com/assets/20171075/24080018/c9ceeebc-0cb7-11e7-9121-7919e9476a86.png)

**Comment by latifisalar** [comment]
Is your LeNet-5 network also trained on the 227*227 RGB inputs? If not, that might be the bug causing the problem, because network parameters and the input network receives are not matched together, because, original LeNet-5 is trained on 28*28 grey-scale images.
Please change the inputs accordingly and test again and let me know if you still have any problem.

**Comment by DanikKamilov** [comment]
Oh, yes. problem solved. thank you
