### ISSUE TITLE
SqueezeNet1.1 on CNNdroid

### ISSUE THREAD

**Issue by YaoQ** [ENCP/CNNdroid#16]
Hi, All
I am  trying to use SqueezeNetV1.1 on CNNdroid. 

I use `SavePycaffeModelInMessagePack.py`  python script to generate the messages based on SqueezeNetV1.1 caffemodel, and it generated **model_param_conv10.msg** and **model_param_conv1.msg**, then I deploy these file into CaffeNet Demo APP.

But it make demo APP crash.
So is there anybody manage to use SqueezeNet on CNNdorid and any advices?

Thank you very much.

**Comment by latifisalar** [comment]
Hi,
SqueezeNet CNNs currently are not supported, they have a mixture of 1x1 and 3x3 filters in their expand convolution layers which CNNdroid can not handle yet, but as discussed in [https://github.com/ENCP/CNNdroid/issues/1#issuecomment-287867501](https://github.com/ENCP/CNNdroid/issues/1#issuecomment-287867501) the support will be added soon.

Thanks

**Comment by YaoQ** [comment]
Thanks for your reply.
