### ISSUE TITLE
PrepareModel function takes times

### ISSUE THREAD

**Issue by joyyang1215** [ENCP/CNNdroid#17]
When I load the CaffeNet Demo, the loading time is about 20 sec on SAMSUNG GALAXY S7.
Is there any solution to solve this problem?

Or, anything I forgot to check?

**Comment by latifisalar** [comment]
Unfortunately, we can not speed up the loading time, we're using binary format to load them as fast as possible, and also trying to keep the data online during the whole application runtime to prevent numerous load times, but you can use NIN model which has the same accuracy as the CaffeNet but has much lower amount of data to be loaded, so the loading time should be shorter.

**Comment by joyyang1215** [comment]
latifisalar, thank you so much.
