### ISSUE TITLE
Can CNNdroid support R-CNN

### ISSUE THREAD

**Issue by hirorogithub** [ENCP/CNNdroid#20]
Hi,R-CNN was supported in caffe ,and CNNdroid seems to support caffe and almost all CNN ,but it actually support R-CNN?how can I get  the exactly support list of CNNdroid?

**Comment by latifisalar** [comment]
Hi,
Unfortunately, not yet. CNNdroid currently supports only plain CNNs like AlexNet or NIN. The ones like SqueezeNet or ResNet which have bypassing or convolution layers with different kernel sizes, are not supported yet. R-CNN is also not supported yet.
Thanks

**Comment by hirorogithub** [comment]
thank you so much for your explain.
