### ISSUE TITLE
Could you tell me what does the "F4F1", "F4F2", "F4F4", "F4F8", "F8F1", "F8F2", "F8F4", "F8F8",words in convolution mean?

### ISSUE THREAD

**Issue by akbarxie** [ENCP/CNNdroid#24]
I am leaning CNNdroid code ,but I cannot figure out the "F4F1", "F4F2", "F4F4", "F4F8", "F8F1", "F8F2", "F8F4", "F8F8",words mean 
takes F4F1 as example:
    I find in function in "initKernelF4F1" in file Convolution.java,

`int c_k_4 = c_k;
        if (c_k % 4 != 0)
            c_k_4 = c_k + 4 - c_k % 4;`
I find maybe is used for init kernel,but I am still confused it.

**Comment by latifisalar** [comment]
Hi,
The FXFY keyword is used to describe the granularity of the kernel execution, it controls the vector size for loading inputs(X) and the number of outputs(Y) to be calculated by each kernel thread.
The code snippet that you have mentioned, is used for determining the necessary amount of zero padding for the input data in case the size of data is not aligned with the pre-defined vector size.
Thanks.

**Comment by akbarxie** [comment]
thanks a lot!
