### ISSUE TITLE
SavePycaffeModelInMessagePack.py crashed

### ISSUE THREAD

**Issue by liuyi999111** [ENCP/CNNdroid#3]
When I convert caffe model files, It's crashed. There is some information:
python(68083,0x7fffa53b73c0) malloc: *** malloc_zone_unregister() failed for 0x7fffa53ad000
Illegal instruction: 4
OS: macOs 10.12.1

**Comment by latifisalar** [comment]
Can you let me know which CNN you tried to convert?

**Comment by liuyi999111** [comment]
My fellow give it to me. It used to detect key points in a face.
[caffmodle2cnndroid.zip](https://github.com/ENCP/CNNdroid/files/565511/caffmodle2cnndroid.zip)
 I find it crash when execute this line `import caffe`.

**Comment by mkaskov** [comment]
# Make sure that Caffe is on the python path:
# Caffe installation path:
caffe_root = '/home/user/caffe/'

Caffe must installed on your system and **caffe_root** is path to folder to your Caffe installation.

**Comment by latifisalar** [comment]
I successfully converted your Caffe model with the provided script.
As Maxim also suggested the problem should be with your pycaffe or path variable setup.

**Comment by liuyi999111** [comment]
the problem be with my pycaffe
