### ISSUE TITLE
SavePycaffeModelInMessagePack.py, Index out of range Error

### ISSUE THREAD

**Issue by cscyangj** [ENCP/CNNdroid#34]
HI, I got following error msg when convert the caffe model. 

Traceback (most recent call last):
  File "SavePycaffeModelInMessagePack.py", line 56, in <module>
    params = get_params(net)
  File "SavePycaffeModelInMessagePack.py", line 42, in get_params
    net_params[key] = [net.params[key][0].data, net.params[key][1].data]
IndexError: Index out of range

can u help have a look with model attached.

[models.zip](https://github.com/ENCP/CNNdroid/files/1456250/models.zip)

**Comment by latifisalar** [comment]
Hi, sorry for late response.
Unfortunately, this model uses PReLU layer, which is not yet supported in the CNNdroid.
I can help if you want to implement it yourself.

Thanks

**Comment by cscyangj** [comment]
okay， thanks， @latifisalar
