### ISSUE TITLE
Is it run on PINE A64 board?

### ISSUE THREAD

**Issue by seokmin1017** [ENCP/CNNdroid#6]
I want to run CNNdroid on PINE A64 board. But I'm not sure because pine 64 board use Mali-400 MP2, not T600. 
Mali-400 can't use openCL, openCV, it use only openGL 1.1.  I think I can't run CNNdroid on pine A64 board....  

I want to hear your opinion. Is it work on PINE64 board?

**Comment by latifisalar** [comment]
CNNdroid uses Android's Renderscript framework, so it's necessary to have a runnig Android OS 5± in order to use it.
About the Mali-400, we have not tested CNNdroid on it, because it was available on older generation of smartphones which usually had an ineligible Android version.
